const Portfolio_data = [

  {
    id: 0,
    category: "Web APPLICATION",
    totalLike: "750",
    title: "Shop Management System",
    image: "./image/shop.png",
    desc: "Feature: Authentication, Profile, Admin Panel, Search, Shop Stock, Godown Stock, Invoice or Bill, Transaction(Debit, Credit), Combined Ledger, Purchase Return, Contact.",
    platform: "HTML, CSS, Bootstrap, JavaScript, Jquery, Ajax, PHP Laravel, MySQL (Web).",
    github: "https://github.com/abunaiim25/ShopnoEnterprise_ShopManagement.git",
    view: "https://github.com/abunaiim25/ShopnoEnterprise_ShopManagement.git",
  },
  {
    id: 1,
    category: "Web APPLICATION",
    totalLike: "750",
    title: "This is AgroBd (Agricultural Shop), It's created for online agricultural business ",
    image: "./image/agrobd.png",
    desc: "Feature: Authentication, Profile, Admin Panel, Search, Users Business Shop, Users Business Profile, Admin Shop, Category wise Product, Product Details, Checkout, Contact, Cart, Payment, Wishlist, Favorite, Order, Discount, Rating, Review, News, About.",
    platform: " HTML, CSS, Bootstrap, JavaScript, Jquery, PHP Laravel, MySQL (Web).",
    github: "https://github.com/abunaiim25/AgroBd-Laravel-Web",
    view: "https://github.com/abunaiim25/AgroBd-Laravel-Web",
  },
  {
    id: 2,
    category: "Web APPLICATION",
    totalLike: "750",
    title: "This is ecommerce website, users all things buy this site",
    image: "./image/ecommerce.png",
    desc: "Feature: Authentication, Profile, Admin Panel, Search, Shop, Category wise Product, Product Details, Checkout, Contact, Cart, Payment, Wishlist, Favorite, Order, Discount, Rating, Review, News, About.",
    platform: "HTML, CSS, Bootstrap, JavaScript, Jquery, PHP Laravel, MySQL (Web).",
    github: "https://github.com/abunaiim25/Online-Marketing-Laravel-Web",
    view: "https://github.com/abunaiim25/Online-Marketing-Laravel-Web",
  },
  {
    id: 3,
    category: "WebSite",
    totalLike: "600",
    title: "The is Portfolio website, My all information here in this website",
    image: "./image/portfolio.png",
    desc: "Feature: About Me, Skills, Job, Projects, Education, Story, Contact.",
    platform: " Tools: HTML, CSS, Bootstrap, React.js (Web).",
    github: "https://github.com/abunaiim25/AbuNaiim-React",
    view: "https://abu-naiim.netlify.app/",
  },
  {
    id: 4,
    category: "Web Application",
    totalLike: "600",
    title: "The is Disease Predictor, You can predictet your disease through this application",
    image: "./image/disease.png",
    desc: "Feature: Authentication, Profile, Admin Panel, About Disease, Symptoms to find disease, Diabetics prediction, Heart disease prediction, cancer prediction, Support.",
    platform: " Tools: Machine Learning (AI), HTML, CSS, Bootstrap, JavaScript, Jquery, Django, MySQL (Web).",
    github: "https://github.com/abunaiim25/Disease-prediction-system",
    view: "https://github.com/abunaiim25/Disease-prediction-system",
  },
  {
    id: 5,
    category: "Web Application",
    totalLike: "600",
    title: "The is Relation.com, Relation.com(Blog Post like social media)",
    image: "./image/relation.png",
    desc: "Feature: Authentication, My Profile, Admin Panel, Search, Post Blog About Relation.",
    platform: " Tools: HTML, CSS, Bootstrap, JavaScript, Jquery, PHP, MySQL (Web).",
    github: "https://github.com/abunaiim25/Relation.com/tree/main",
    view: "https://github.com/abunaiim25/Relation.com/tree/main",
  },
  {
    id: 6,
    category: "Web Application",
    totalLike: "600",
    title: "The is Daffodil Media, Daffodil Media (Like Social Media)",
    image: "./image/daffodil.png",
    desc: "Feature: Authentication, My Profile, Admin Panel, Search, Post About DIU.",
    platform: " Tools: HTML, CSS, Bootstrap, JavaScript, Jquery, React.js, Laravel, MySQL (Web).",
    github: "https://github.com/abunaiim25/DaffodilMedia",
    view: "https://github.com/abunaiim25/DaffodilMedia",
  },
  {
    id: 7,
    category: "Mobile Application",
    totalLike: "600",
    title: "This is TV and News Paper app, I think you enjoy through this app",
    image: "./image/tvapp.jpg",
    desc: "Feature: Online Tv, Online Newspaper.",
    platform: "XML, Java (Android).",
    github: "https://github.com/abunaiim25/NetBd-2.0.git",
    view: "https://github.com/abunaiim25/NetBd-2.0.git",
  },
  {
    id: 8,
    category: "WebSite",
    totalLike: "600",
    title: "The is BMI Calculator, Through this calculator you can make sure your health",
    image: "./image/bmi.png",
    desc: "Feature: BMI Calculation, BMI Ranges, Feet to Centimeter, Meter to Centimeter.",
    platform: " HTML, CSS, Bootstrap, JavaScript (Web).",
    github: "https://github.com/abunaiim25/Health-Maintain-Web",
    view: "https://health-maintain.netlify.app/",
  },
  {
    id: 9,
    category: "WebSite",
    totalLike: "750",
    title: "This is Simple Calculator, I think you enjoy through this calculator",
    image: "./image/calculator.PNG",
    desc: "Normal Calculation.",
    platform: "HTML, CSS, Bootstrap, JavaScript (Web).",
    github: "https://github.com/abunaiim25/Calculator-Website",
    view: "https://naiim-calculator.netlify.app/",
  },
]
export default Portfolio_data
